name: staff_mate
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^3.1.0  
  google_fonts: ^6.2.1
  http: ^1.2.2
  shared_preferences: ^2.5.3
  camera: ^0.10.5
  intl: ^0.17.0
  provider: ^6.1.3
  flutter_staggered_animations: ^1.1.1
  image_picker: ^1.2.0
  permission_handler: ^12.0.1
  speech_to_text: ^7.3.0
  url_launcher: ^6.1.10
  flutter_typeahead: ^5.0.0
  line_icons: ^2.0.1
  webview_flutter: ^4.4.4
  webview_flutter_android: ^4.10.1
  webview_flutter_wkwebview: ^3.23.0
  flutter_secure_storage: ^10.0.0
  flutter_tts: ^4.2.5
  local_auth: ^2.3.0
  iconsax: ^0.0.8
  file_picker: ^10.3.10
  image_pickers: ^2.0.6
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/logosm.png
    - assets/images/welcomesm.png
    - assets/images/avtar.png
    - assets/images/welcome-removebg-preview.png

    